# Generated by Django 4.2.11 on 2026-02-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_style', models.TextField(blank=True, help_text='Maelezo ya mtindo maalum', null=True)),
                ('size', models.CharField(choices=[('NDOGO', 'Ndogo'), ('KATI', 'Saizi ya Kati'), ('KUBWA', 'Kubwa'), ('CUSTOM', 'Vipimo maalum')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri'), ('APPROVED', 'Imekubaliwa'), ('IN_PROGRESS', 'Inaendelea'), ('COMPLETED', 'Imemaliza'), ('DELIVERED', 'Imetumwa'), ('REJECTED', 'Imekataliwa'), ('CANCELLED', 'Imesitishwa')], default='PENDING', max_length=15)),
                ('kifua', models.DecimalField(blank=True, decimal_places=2, help_text='Kipimo cha kifua (cm)', max_digits=5, null=True)),
                ('mkono', models.DecimalField(blank=True, decimal_places=2, help_text='Urefu wa mkono (cm)', max_digits=5, null=True)),
                ('kiuno', models.DecimalField(blank=True, decimal_places=2, help_text='Kipimo cha kiuno (cm)', max_digits=5, null=True)),
                ('mguu', models.DecimalField(blank=True, decimal_places=2, help_text='Urefu wa mguu (cm)', max_digits=5, null=True)),
                ('urefu', models.DecimalField(blank=True, decimal_places=2, help_text='Urefu wa jumla (cm)', max_digits=5, null=True)),
                ('shingo', models.DecimalField(blank=True, decimal_places=2, help_text='Kipimo cha shingo (cm)', max_digits=5, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Tarehe ya kupokea nguo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Oda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomStyleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Pakia picha ya mtindo unaotaka', upload_to='custom_styles/', verbose_name='Picha ya Mtindo')),
                ('description', models.TextField(help_text='Eleza mtindo unaoutaka kwa undani', verbose_name='Maelezo')),
                ('preferred_fabric', models.CharField(blank=True, help_text='Andika aina ya kitambaa unalopenda (kama unalijua)', max_length=100, null=True, verbose_name='Kitambaa Kinachopendwa')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bei iliyokadiriwa na mshonaji', max_digits=10, null=True, verbose_name='Bei ya Makadirio')),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri'), ('APPROVED', 'Imekubaliwa'), ('REJECTED', 'Imekataliwa')], default='PENDING', max_length=15, verbose_name='Hali')),
                ('admin_notes', models.TextField(blank=True, help_text='Maoni kutoka kwa mshonaji', null=True, verbose_name='Maoni ya Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Kuunda')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tarehe ya Kubadilisha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_style_requests', to=settings.AUTH_USER_MODEL, verbose_name='Mteja')),
            ],
            options={
                'verbose_name': 'Ombi la Mtindo Maalum',
                'verbose_name_plural': 'Maombi ya Mitindo Maalum',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='orders.order')),
            ],
        ),
    ]
