# Generated by Django 4.2.11 on 2026-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Maelezo ya mtindo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('kiume', 'Nguo za Kiume'), ('kike', 'Nguo za Kike'), ('zote', 'Nguo za Kiume na Kike')], default='zote', max_length=10)),
                ('category', models.CharField(choices=[('shati', 'Shati'), ('suruali', 'Suruali'), ('kanzu', 'Kanzu'), ('vitenge', 'Vitenge'), ('sare', 'Sare'), ('gauni', 'Gauni'), ('koti', 'Koti'), ('nyingine', 'Nyingine')], default='nyingine', max_length=20)),
                ('image', models.ImageField(upload_to='styles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mtindo',
                'verbose_name_plural': 'Mitindo',
                'ordering': ['-created_at'],
            },
        ),
    ]
