# Generated by Django 4.2.11 on 2026-02-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Andika maoni yako kuhusu huduma uliyopata', verbose_name='Maoni')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], help_text='Kiwango cha kuridhika (1-5)', null=True, verbose_name='Kiwango')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya kuwasilisha')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order', verbose_name='Oda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Mteja')),
            ],
            options={
                'verbose_name': 'Maoni',
                'verbose_name_plural': 'Maoni',
                'ordering': ['-created_at'],
            },
        ),
    ]
